const myWatchedSeries = ["black mirror", "money heist", "the big bang theory"];
var myWatchedSeriesLength = myWatchedSeries.length;
var myWatchedSeriesSentence = myWatchedSeries.join(", ");
// console.log("ive watched 3 series :", myWatchedSeriesSentence);
myWatchedSeries [2]= "friends";
myWatchedSeries.push("stranger things");
myWatchedSeries.unshift("breaking bad");
delete myWatchedSeries [1];
// console.log("money heist"[2]);
console.log(myWatchedSeries);
